### ISSUE TITLE
Switched weight in List of Topics

### ISSUE THREAD

**Issue by Temitayooyelowo** [willfindlay/4109final#15]
**security models/goals** should be worth **about 10%** while secret key crypto is worth **about 18%** 

It's flipped in the list of topics 

https://github.com/willfindlay/4109final/blob/bc1472b7e5d887507953c9936a2a5ef1ac494bcb/study.rmd#L68
https://github.com/willfindlay/4109final/blob/bc1472b7e5d887507953c9936a2a5ef1ac494bcb/study.rmd#L70

**Comment by willfindlay** [comment]
Fixed, thank you for noticing!
